apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-airflow-chart.fullname" . }}-secrets
type: Opaque
data:
  AIRFLOW__CORE__FERNET_KEY: {{ .Values.airflow.config.AIRFLOW__CORE__FERNET_KEY | b64enc | quote }}