apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-airflow-chart.fullname" . }}-webserver
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "my-airflow-chart.name" . }}
    component: webserver