import_template:
  ATOM_POS_SET_TXN:
    header:
      - "Created time"
      - "customer name"
      - "master merchant"
      - "mid"
      - "tid"
      - "serial no"
      - "batch no"
      - "invoice no"
      - "Card number"
      - "card type"
      - "card origin"
      - "Request amount"
      - "is settle"
      - "is void"
      - "is reversal"
      - "auth id reponse"
      - "bank code"
      - "original transaction date"
      - "response code"
      - "retrieval ref no"
      - "settle unix time"
      - "txn id"
      - "void txn id"
      - "void unix time"
      - "reversal txn id"
      - "reversal time"
      - "fee merchant"
      - "fee master merchant"
      - "Cost price"
      - "Industry"
      - "Routing bank code"
      - "transaction type"
      - "Pos entry mode"
      - "Sharing Merchant Fee"
      - "Sharing ACQ Bank Fee"
      - "bvb credit amt"
      - "Discount Fee"
      - "Merchant Credit Amount"
      - "Account Number"
      - "Account Name"
    file_extension: "xlsx"
    separate: "|"
    sftp_conn: "SFTP_ACQ_POS"
    sftp_move: true
    start_row: 2
    end_row: 0
    start_col: 1
    end_col: 0
    is_read_to_empty_row: true
    table_name: "dw.vccb_atom_pos_settl_txn_tmp"
    is_truncate_tmp_table: true
    procedure_name: "bvbpks_Acq_Pos_Api.Pr_Imp_atom_pos_settl_txn"
    external_process: ""
    column_mapping:
      "Created time": "record_date"
      "customer name": "merchant_name"
      "master merchant": "master_merchant"
      "mid": "merchant_id"
      "tid": "terminal_id"
      "serial no": "serial_no"
      "batch no": "batch_no"
      "invoice no": "invoice_no"
      "Card number": "Card_number"
      "card type": "card_type"
      "card origin": "card_origin"
      "Request amount": "Request_amount"
      "is settle": "is_settle"
      "is void": "is_void"
      "is reversal": "is_reversal"
      "auth id reponse": "auth_id_reponse"
      "bank code": "issuer_bank"
      "original transaction date": "orig_txn_date"
      "response code": "response_code"
      "retrieval ref no": "retrieval_ref_no"
      "settle unix time": "settle_unix_time"
      "txn id": "txn_id"
      "void txn id": "void_txn_id"
      "void unix time": "void_unix_time"
      "reversal txn id": "reversal_txn_id"
      "reversal time": "reversal_time"
      "fee merchant": "merchant_fee_rate"
      "fee master merchant": "master_merchant_fee_rate"
      "Cost price": "Cost_price_rate"
      "Industry": "MCC"
      "Routing bank code": "acq_bank_code"
      "transaction type": "transaction_type"
      "Pos entry mode": "Pos_entry_mode"
      "Sharing Merchant Fee": "master_merchant_fee"
      "Sharing ACQ Bank Fee": "acq_bank_fee"
      "bvb credit amt": "bvb_credit_amt"
      "Discount Fee": "discount_amt"
      "Merchant Credit Amount": "merchant_credit_amt"
      "Account Number": "account_number"
      "Account Name": "account_name"
  ACQ_BANK_BENEFIT:
    header:
      - "Bank Name"
      - "ACQ_BANK_CODE"
      - "Tax code"
      - "Address"
      - "Contract"
      - "Nostro Account"
      - "Clearing Branch Code"
      - "Clearing Account Number"
      - "Clearing Account Name"
      - "suspense Branh Code"
      - "suspense Account Number"
      - "suspense Account Name"
      - "Receivable Branch Code"
      - "Receivable Account Number"
      - "Receivable Account Name"
      - "Payable Branch Code"
      - "Payable Account Number"
      - "Payable Account Name"
      - "Deposit Branch Code"
      - "Deposit Account Number"
      - "Deposit Account Name"
    file_extension: "xlsx"
    separate: "|"
    sftp_conn: "SFTP_ACQ_POS"
    sftp_move: true
    start_row: 3
    end_row: 0
    start_col: 2
    end_col: 0
    is_read_to_empty_row: true
    table_name: "dw.VCCB_ACQ_BANK_BENEFIT_ACCT_TMP"
    is_truncate_tmp_table: true
    procedure_name: "bvbpks_Acq_Pos_Api.Pr_Imp_acq_bank_benefit_acct"
    external_process: ""
    column_mapping:
      "Bank Name": "Bank_Name"
      "ACQ_BANK_CODE": "ACQ_BANK_CODE"
      "Tax code": "Tax_code"
      "Address": "Address"
      "Contract": "Contract"
      "Nostro Account": "Nostro_Account"
      "Clearing Branch Code": "Clearing_Branch_Code"
      "Clearing Account Number": "Clearing_Account_Number"
      "Clearing Account Name": "Clearing_Account_Name"
      "suspense Branh Code": "suspense_Branh_Code"
      "suspense Account Number": "suspense_Account_Number"
      "suspense Account Name": "suspense_Account_Name"
      "Receivable Branch Code": "Receivable_Branch_Code"
      "Receivable Account Number": "Receivable_Account_Number"
      "Receivable Account Name": "Receivable_Account_Name"
      "Payable Branch Code": "Payable_Branch_Code"
      "Payable Account Number": "Payable_Account_Number"
      "Payable Account Name": "Payable_Account_Name"
      "Deposit Branch Code": "Deposit_Branch_Code"
      "Deposit Account Number": "Deposit_Account_Number"
      "Deposit Account Name": "Deposit_Account_Name"
  ACQ_STB_RECONCILIATION:
    header:
      - "MERCHANT_ID"
      - "MM_DBA_NAME"
      - "TERMINAL_ID"
      - "BATCH_NO"
      - "InvoiceNo"
      - "SETTLE_DATE"
      - "SETTLE_TIME"
      - "TRANS_DATE"
      - "TRANS_TIME"
      - "CARDNO"
      - "TRANS_AMOUNT"
      - "CURR_RATE"
      - "BILLING_AMOUNT"
      - "DISCOUNT"
      - "NET_AMOUNT"
      - "APPROVE_CODE"
      - "APPROVE_CODE_SALE"
      - "PROC_DATE"
      - "BOOK_DATE"
      - "DISCOUNT_RATE"
      - "CrdType"
      - "STATUS"
      - "MM_BIZ_NAME"
      - "ACQRefNo"
      - "ReqRecId"
      - "Customer_Description"
      - "Reference_No"
      - "Bill_Code"
      - "Customer_Name"
      - "Service_cd"
      - "Real_card"
      - "QR/SSP"
      - "transactionid"
      - "PosEntry"
      - "CURR_TYPE"
      - "ORDER_ID"
    file_extension: "xlsx"
    separate: "|"
    sftp_conn: "SFTP_ACQ_POS"
    sftp_move: true
    start_row: 2
    end_row: 0
    start_col: 1
    end_col: 0
    is_read_to_empty_row: true
    table_name: "dw.vccb_reconciliation_stb_tmp"
    is_truncate_tmp_table: true
    procedure_name: "bvbpks_Acq_Pos_Api.pr_imp_reconciliation_stb"
    external_process: ""
    column_mapping:
      "MERCHANT_ID": "MERCHANT_ID"
      "MM_DBA_NAME": "MM_DBA_NAME"
      "TERMINAL_ID": "TERMINAL_ID"
      "BATCH_NO": "BATCH_NO"
      "InvoiceNo": "Invoice_No"
      "SETTLE_DATE": "SETTLE_DATE"
      "SETTLE_TIME": "SETTLE_TIME"
      "TRANS_DATE": "TRANS_DATE"
      "TRANS_TIME": "TRANS_TIME"
      "CARDNO": "CARD_NO"
      "TRANS_AMOUNT": "TRANS_AMOUNT"
      "CURR_RATE": "CURR_RATE"
      "BILLING_AMOUNT": "BILLING_AMOUNT"
      "DISCOUNT": "DISCOUNT"
      "NET_AMOUNT": "NET_AMOUNT"
      "APPROVE_CODE": "APPROVE_CODE"
      "APPROVE_CODE_SALE": "APPROVE_CODE_SALE"
      "PROC_DATE": "PROC_DATE"
      "BOOK_DATE": "BOOK_DATE"
      "DISCOUNT_RATE": "DISCOUNT_RATE"
      "CrdType": "Crd_Type"
      "STATUS": "STATUS"
      "MM_BIZ_NAME": "MM_BIZ_NAME"
      "ACQRefNo": "ACQ_Ref_No"
      "ReqRecId": "Req_Rec_Id"
      "Customer_Description": "Customer_Description"
      "Reference_No": "Reference_No"
      "Bill_Code": "Bill_Code"
      "Customer_Name": "Customer_Name"
      "Service_cd": "Service_cd"
      "Real_card": "Real_card"
      "QR/SSP": "QR_SSP"
      "transactionid": "transaction_id"
      "PosEntry": "Pos_Entry"
      "CURR_TYPE": "CURR_TYPE"
      "ORDER_ID": "ORDER_ID"
  ACQ_VPB_RECONCILIATION:
    header:
      - "MERCHANT_ID"
      - "TERMINAL_ID"
      - "TRANS_TYPE"
      - "REQUEST_CATEGORY"
      - "TRANSACTION_DATETIME"
      - "AUTH_CODE"
      - "ACCOUNT_NUMBER"
      - "CARD_TYPE"
      - "CURR"
      - "AMOUNT"
      - "FEE"
      - "VAT"
      - "RET_REF_NUMBER"
      - "POSTING_STATUS"
      - "TRANS_CONDITION"
      - "CONTRACT_NAME"
      - "MPGSORDERID"
      - "CYBERSORDERID"
      - "CYBERSPURCHID"
    file_extension: "xlsx"
    separate: "|"
    sftp_conn: "SFTP_ACQ_POS"
    sftp_move: true
    start_row: 2
    end_row: 0
    start_col: 1
    end_col: 0
    is_read_to_empty_row: true
    table_name: "dw.vccb_reconciliation_vpb_tmp"
    is_truncate_tmp_table: true
    procedure_name: "bvbpks_Acq_Pos_Api.pr_imp_reconciliation_vpb"
    external_process: ""
    column_mapping:
      MERCHANT_ID: "MERCHANT_ID"
      TERMINAL_ID: "TERMINAL_ID"
      TRANS_TYPE: "TRANS_TYPE"
      REQUEST_CATEGORY: "REQUEST_CATEGORY"
      TRANSACTION_DATETIME: "TRANS_DATETIME"
      AUTH_CODE: "APPROVE_CODE"
      ACCOUNT_NUMBER: "CARD_NO"
      CARD_TYPE: "CRD_TYPE"
      CURR: "CURR_TYPE"
      AMOUNT: "TRANS_AMOUNT"
      FEE: "FEE_AMOUNT"
      VAT: "VAT_AMOUNT"
      RET_REF_NUMBER: "REFERENCE_NO"
      POSTING_STATUS: "STATUS"
      TRANS_CONDITION: "TRANS_CONDITION"
      CONTRACT_NAME: "CONTRACT_NAME"
      MPGSORDERID: "ORDER_ID"
      CYBERSORDERID: "CYBERS_ORDER_ID"
      CYBERSPURCHID: "CYBERS_PURCH_ID"
  ACQ_POS_MDR_FEE:
    header:
      - "CODE"
      - "NAPAS"
      - "VISA_ACQ_BANK"
      - "VISA_ISS_domestic"
      - "VISA_ISS_Foreign"
      - "MASTER_ACQ_BANK"
      - "MASTER_ISS_domestic"
      - "MASTER_ISS_Foreign"
      - "JCB_ACQ_BANK"
      - "JCB_ISS_domestic"
      - "JCB_ISS_Foreign"
    file_extension: "xlsx"
    separate: "|"
    sftp_conn: "SFTP_ACQ_POS"
    sftp_move: true
    start_row: 2
    end_row: 0
    start_col: 1
    end_col: 0
    is_read_to_empty_row: true
    table_name: "dw.VCCB_ACQ_MDR_FEE_TMP_IMP"
    is_truncate_tmp_table: true
    procedure_name: "bvbpks_Acq_Pos_Api.pr_imp_Mdr_Fee"
    external_process: ""
    column_mapping:
      "CODE": "MDR_FEE_CODE"
      "NAPAS": "NAPAS_FEE"
      "VISA_ACQ_BANK": "VISA_ACQ_FEE"
      "VISA_ISS_domestic": "VISA_ISS_DOMESTIC_FEE"
      "VISA_ISS_Foreign": "VISA_ISS_FOREIGN_FEE"
      "MASTER_ACQ_BANK": "MASTER_ACQ_FEE"
      "MASTER_ISS_domestic": "MASTER_ISS_DOMESTIC_FEE"
      "MASTER_ISS_Foreign": "MASTER_ISS_FOREIGN_FEE"
      "JCB_ACQ_BANK": "JCB_ACQ_FEE"
      "JCB_ISS_domestic": "JCB_ISS_DOMESTIC_FEE"
      "JCB_ISS_Foreign": "JCB_ISS_FOREIGN_FEE"
  ACQ_BANK_FEE:
    header:
      - "CODE"
      - "NAPAS"
      - "VISA_ACQ_BANK"
      - "VISA_ISS_domestic"
      - "VISA_ISS_Foreign"
      - "MASTER_ACQ_BANK"
      - "MASTER_ISS_domestic"
      - "MASTER_ISS_Foreign"
      - "JCB_ACQ_BANK"
      - "JCB_ISS_domestic"
      - "JCB_ISS_Foreign"
    file_extension: "xlsx"
    separate: "|"
    sftp_conn: "SFTP_ACQ_POS"
    sftp_move: true
    start_row: 2
    end_row: 0
    start_col: 1
    end_col: 0
    is_read_to_empty_row: true
    table_name: "dw.VCCB_ACQ_BANK_FEE_TMP_IMP"
    is_truncate_tmp_table: true
    procedure_name: "bvbpks_Acq_Pos_Api.pr_imp_ACQ_Bank_Fee"
    external_process: ""
    column_mapping:
      "CODE": "BANK_CODE"
      "NAPAS": "NAPAS_FEE"
      "VISA_ACQ_BANK": "VISA_ACQ_FEE"
      "VISA_ISS_domestic": "VISA_ISS_DOMESTIC_FEE"
      "VISA_ISS_Foreign": "VISA_ISS_FOREIGN_FEE"
      "MASTER_ACQ_BANK": "MASTER_ACQ_FEE"
      "MASTER_ISS_domestic": "MASTER_ISS_DOMESTIC_FEE"
      "MASTER_ISS_Foreign": "MASTER_ISS_FOREIGN_FEE"
      "JCB_ACQ_BANK": "JCB_ACQ_FEE"
      "JCB_ISS_domestic": "JCB_ISS_DOMESTIC_FEE"
      "JCB_ISS_Foreign": "JCB_ISS_FOREIGN_FEE"
  IMP_MERCHANT_INFO:
    header:
      - "BLANK"
      - "STT"
      - "ACQ_BANK"
      - "MERCHANT_CODE"
      - "CIF_NUMBER"
      - "SALE_CODE"
      - "BANK_BRANCH_NAME"
      - "MERCHANT_ID"
      - "TERMINAL_ID"
      - "MERCHANT_NAME"
      - "STREET_ADDR"
      - "WARD_ADDR"
      - "DISTRICT_ADDR"
      - "CITY_ADDR"
      - "BUSINESS_TYPE"
      - "MCC"
      - "BANK_ACCOUNT_NUMBER"
      - "BANK_ACCOUNT_NAME"
      - "PHONE_NUMBER"
      - "EMAIL"
      - "BANK_CODE"
      - "MDR_FEE_CODE"
      - "IS_NEW_POS"
      - "POS_ASSET_CODE"
      - "POS_PRODUCT"
      - "POS_TYPE"
      - "SERIAL"
    file_extension: "xlsx"
    separate: "|"
    sftp_conn: "SFTP_ACQ_POS"
    sftp_move: true
    start_row: 7
    end_row: 0
    start_col: 3
    end_col: 0
    is_read_to_empty_row: true
    table_name: "dw.VCCB_ACQ_POS_MERCHANT_IMP_TMP"
    is_truncate_tmp_table: true
    procedure_name: ""
    external_process: ""
    column_mapping: {}
  DEFAULT:
    header:
    file_extension: "xlsx"
    separate: "|"
    sftp_conn: ""
    sftp_move: true
    start_row: 2
    end_row: 0
    start_col: 1
    end_col: 0
    is_read_to_empty_row: true
    table_name: ""
    is_truncate_tmp_table: true
    procedure_name: ""
    external_process: ""
    column_mapping: {}
